"""add user email

Revision ID: 139793354d51
Revises: 395a4ec41a5f
Create Date: 2024-10-02 13:13:17.194704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '139793354d51'
down_revision: Union[str, None] = '395a4ec41a5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_users', sa.Column('email', sa.String(length=30), nullable=True))
    op.create_unique_constraint('uix_service_user_email', 'service_users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_service_user_email', 'service_users', type_='unique')
    op.drop_column('service_users', 'email')
    # ### end Alembic commands ###
