"""add unique usernmae

Revision ID: 6293ff2a0078
Revises: 873d5bd44465
Create Date: 2024-09-30 11:35:44.745615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6293ff2a0078'
down_revision: Union[str, None] = '873d5bd44465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_service_user_username', 'service_users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_service_user_username', 'service_users', type_='unique')
    # ### end Alembic commands ###
