"""add created_at index

Revision ID: 395a4ec41a5f
Revises: e61f5c9dcc8d
Create Date: 2024-09-30 13:19:33.786159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '395a4ec41a5f'
down_revision: Union[str, None] = 'e61f5c9dcc8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_service_user_created_at', 'service_users', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_service_user_created_at', table_name='service_users')
    # ### end Alembic commands ###
